# Generated by Django 4.2.6 on 2023-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
