# Generated by Django 4.2.6 on 2023-10-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('review_vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('NO', 'No action'), ('LK', 'Liked'), ('DK', 'Disliked')], default='NO', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='review_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Review.reviewvote'),
        ),
    ]
