# Generated by Django 4.2.6 on 2023-12-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_order_item'),
        ('Review', '0003_remove_review_product_review_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
