# Generated by Django 4.2.6 on 2023-12-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_orderitem_product'),
        ('Review', '0004_remove_review_order_item_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='orderitem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderitem'),
        ),
    ]
