# Generated by Django 4.2.6 on 2023-12-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0005_remove_review_product_review_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'To be Reviewed'), (1, 'Reviewed')], null=True),
        ),
    ]
