# Generated by Django 4.2.6 on 2023-12-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0006_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
