# Generated by Django 4.2.6 on 2023-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0008_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
