# Generated by Django 4.2.6 on 2023-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0009_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
