# Generated by Django 4.2.6 on 2023-12-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0010_review_date_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
