# Generated by Django 4.2.6 on 2023-10-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name_plural': 'Ticket category'},
        ),
    ]
