# Generated by Django 4.2.6 on 2023-12-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_orderitem_review_id_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'To be Reviewed'), (1, 'Reviewed')], null=True),
        ),
    ]
