# Generated by Django 4.2.6 on 2023-12-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
