# Generated by Django 4.2.6 on 2023-12-16 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_address_options_alter_courier_options_and_more'),
        ('Order', '0009_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.customer'),
        ),
    ]
